# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hsq/git/net-sniffer/src/PyQt/qtLearn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1313, 1054)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ListButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.ListButton.setFont(font)
        self.ListButton.setObjectName("ListButton")
        self.horizontalLayout_4.addWidget(self.ListButton)
        self.continueBtn = QtWidgets.QPushButton(self.centralwidget)
        self.continueBtn.setObjectName("continueBtn")
        self.horizontalLayout_4.addWidget(self.continueBtn)
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_4.addWidget(self.stopBtn)
        self.Btnclear = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.Btnclear.setFont(font)
        self.Btnclear.setObjectName("Btnclear")
        self.horizontalLayout_4.addWidget(self.Btnclear)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalList = QtWidgets.QVBoxLayout()
        self.verticalList.setObjectName("verticalList")
        self.verticalLayout.addLayout(self.verticalList)
        self.tableList = QtWidgets.QTableWidget(self.centralwidget)
        self.tableList.setGridStyle(QtCore.Qt.SolidLine)
        self.tableList.setObjectName("tableList")
        self.tableList.setColumnCount(7)
        self.tableList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableList)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.DetailText = QtWidgets.QTextBrowser(self.centralwidget)
        self.DetailText.setObjectName("DetailText")
        self.verticalLayout.addWidget(self.DetailText)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.Binarytext = QtWidgets.QTextBrowser(self.centralwidget)
        self.Binarytext.setObjectName("Binarytext")
        self.verticalLayout.addWidget(self.Binarytext)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1313, 28))
        self.menubar.setObjectName("menubar")
        self.menuSniffer = QtWidgets.QMenu(self.menubar)
        self.menuSniffer.setObjectName("menuSniffer")
        self.menuDetail = QtWidgets.QMenu(self.menubar)
        self.menuDetail.setObjectName("menuDetail")
        self.menuDetal = QtWidgets.QMenu(self.menubar)
        self.menuDetal.setObjectName("menuDetal")
        self.menuBinary = QtWidgets.QMenu(self.menubar)
        self.menuBinary.setObjectName("menuBinary")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSniffer.menuAction())
        self.menubar.addAction(self.menuDetail.menuAction())
        self.menubar.addAction(self.menuDetal.menuAction())
        self.menubar.addAction(self.menuBinary.menuAction())

        self.retranslateUi(MainWindow)
        self.Btnclear.clicked.connect(self.DetailText.clear)
        self.Btnclear.clicked.connect(self.Binarytext.clear)
        self.ListButton.clicked.connect(MainWindow.snip)
        self.stopBtn.clicked.connect(MainWindow.stop)
        self.continueBtn.clicked.connect(MainWindow.conti)
        self.Btnclear.clicked.connect(MainWindow.clearTable)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rukawa"))
        self.label.setText(_translate("MainWindow", "Rukawa Sniffer"))
        self.ListButton.setText(_translate("MainWindow", "Sniffer"))
        self.continueBtn.setText(_translate("MainWindow", "continue"))
        self.stopBtn.setText(_translate("MainWindow", "stop"))
        self.Btnclear.setText(_translate("MainWindow", "Clear"))
        self.label_3.setText(_translate("MainWindow", "Packet List"))
        self.tableList.setSortingEnabled(False)
        item = self.tableList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sniffer count"))
        item = self.tableList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "src"))
        item = self.tableList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "dst"))
        item = self.tableList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "protocol"))
        item = self.tableList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "length"))
        item = self.tableList.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "info"))
        item = self.tableList.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "view"))
        self.label_2.setText(_translate("MainWindow", "Packet Detail"))
        self.DetailText.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.label_4.setText(_translate("MainWindow", "Packet Binary"))
        self.Binarytext.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.menuSniffer.setTitle(_translate("MainWindow", "Sniffer"))
        self.menuDetail.setTitle(_translate("MainWindow", "List"))
        self.menuDetal.setTitle(_translate("MainWindow", "Detal"))
        self.menuBinary.setTitle(_translate("MainWindow", "Binary"))
