# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hsq/git/net-sniffer/src/PyQt/qtLearn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 67, 17))
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuSniffer = QtWidgets.QMenu(self.menubar)
        self.menuSniffer.setObjectName("menuSniffer")
        self.menuDetail = QtWidgets.QMenu(self.menubar)
        self.menuDetail.setObjectName("menuDetail")
        self.menuDetal = QtWidgets.QMenu(self.menubar)
        self.menuDetal.setObjectName("menuDetal")
        self.menuBinary = QtWidgets.QMenu(self.menubar)
        self.menuBinary.setObjectName("menuBinary")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSniffer.menuAction())
        self.menubar.addAction(self.menuDetail.menuAction())
        self.menubar.addAction(self.menuDetal.menuAction())
        self.menubar.addAction(self.menuBinary.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rukawa"))
        self.label.setText(_translate("MainWindow", "Rukawa"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">hello</span></p></body></html>"))
        self.menuSniffer.setTitle(_translate("MainWindow", "Sniffer"))
        self.menuDetail.setTitle(_translate("MainWindow", "List"))
        self.menuDetal.setTitle(_translate("MainWindow", "Detal"))
        self.menuBinary.setTitle(_translate("MainWindow", "Binary"))
