# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hsq/git/net-sniffer/src/PyQt/qtLearn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1313, 1054)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ListButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.ListButton.setFont(font)
        self.ListButton.setObjectName("ListButton")
        self.horizontalLayout_4.addWidget(self.ListButton)
        self.continueBtn = QtWidgets.QPushButton(self.centralwidget)
        self.continueBtn.setObjectName("continueBtn")
        self.horizontalLayout_4.addWidget(self.continueBtn)
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_4.addWidget(self.stopBtn)
        self.Btnclear = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.Btnclear.setFont(font)
        self.Btnclear.setObjectName("Btnclear")
        self.horizontalLayout_4.addWidget(self.Btnclear)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalList = QtWidgets.QVBoxLayout()
        self.verticalList.setObjectName("verticalList")
        self.horizontalListBar = QtWidgets.QHBoxLayout()
        self.horizontalListBar.setObjectName("horizontalListBar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalListBar.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalListBar.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalListBar.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalListBar.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalListBar.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalListBar.addWidget(self.label_10)
        self.verticalList.addLayout(self.horizontalListBar)
        self.verticalLayout.addLayout(self.verticalList)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ListNumber = QtWidgets.QTextBrowser(self.centralwidget)
        self.ListNumber.setObjectName("ListNumber")
        self.horizontalLayout_3.addWidget(self.ListNumber)
        self.ListSrc = QtWidgets.QTextBrowser(self.centralwidget)
        self.ListSrc.setObjectName("ListSrc")
        self.horizontalLayout_3.addWidget(self.ListSrc)
        self.ListDst = QtWidgets.QTextBrowser(self.centralwidget)
        self.ListDst.setObjectName("ListDst")
        self.horizontalLayout_3.addWidget(self.ListDst)
        self.ListLength = QtWidgets.QTextBrowser(self.centralwidget)
        self.ListLength.setObjectName("ListLength")
        self.horizontalLayout_3.addWidget(self.ListLength)
        self.ListProtocol = QtWidgets.QTextBrowser(self.centralwidget)
        self.ListProtocol.setObjectName("ListProtocol")
        self.horizontalLayout_3.addWidget(self.ListProtocol)
        self.ListInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.ListInfo.setObjectName("ListInfo")
        self.horizontalLayout_3.addWidget(self.ListInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.DetailText = QtWidgets.QTextBrowser(self.centralwidget)
        self.DetailText.setObjectName("DetailText")
        self.verticalLayout.addWidget(self.DetailText)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.Binarytext = QtWidgets.QTextBrowser(self.centralwidget)
        self.Binarytext.setObjectName("Binarytext")
        self.verticalLayout.addWidget(self.Binarytext)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1313, 28))
        self.menubar.setObjectName("menubar")
        self.menuSniffer = QtWidgets.QMenu(self.menubar)
        self.menuSniffer.setObjectName("menuSniffer")
        self.menuDetail = QtWidgets.QMenu(self.menubar)
        self.menuDetail.setObjectName("menuDetail")
        self.menuDetal = QtWidgets.QMenu(self.menubar)
        self.menuDetal.setObjectName("menuDetal")
        self.menuBinary = QtWidgets.QMenu(self.menubar)
        self.menuBinary.setObjectName("menuBinary")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSniffer.menuAction())
        self.menubar.addAction(self.menuDetail.menuAction())
        self.menubar.addAction(self.menuDetal.menuAction())
        self.menubar.addAction(self.menuBinary.menuAction())

        self.retranslateUi(MainWindow)
        self.Btnclear.clicked.connect(self.DetailText.clear)
        self.Btnclear.clicked.connect(self.Binarytext.clear)
        self.Btnclear.clicked.connect(self.ListNumber.clear)
        self.Btnclear.clicked.connect(self.ListSrc.clear)
        self.Btnclear.clicked.connect(self.ListDst.clear)
        self.Btnclear.clicked.connect(self.ListLength.clear)
        self.Btnclear.clicked.connect(self.ListProtocol.clear)
        self.Btnclear.clicked.connect(self.ListInfo.clear)
        self.ListButton.clicked.connect(MainWindow.snip)
        self.stopBtn.clicked.connect(MainWindow.stop)
        self.continueBtn.clicked.connect(MainWindow.conti)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rukawa"))
        self.label.setText(_translate("MainWindow", "Rukawa Sniffer"))
        self.ListButton.setText(_translate("MainWindow", "Sniffer"))
        self.continueBtn.setText(_translate("MainWindow", "continue"))
        self.stopBtn.setText(_translate("MainWindow", "stop"))
        self.Btnclear.setText(_translate("MainWindow", "Clear"))
        self.label_3.setText(_translate("MainWindow", "Packet List"))
        self.label_5.setText(_translate("MainWindow", "number"))
        self.label_6.setText(_translate("MainWindow", "src"))
        self.label_7.setText(_translate("MainWindow", "dst"))
        self.label_9.setText(_translate("MainWindow", "length"))
        self.label_8.setText(_translate("MainWindow", "protocol"))
        self.label_10.setText(_translate("MainWindow", "info"))
        self.ListNumber.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">number</p></body></html>',
            )
        )
        self.ListSrc.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">src</p></body></html>',
            )
        )
        self.ListDst.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">dst</p></body></html>',
            )
        )
        self.ListLength.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">length</p></body></html>',
            )
        )
        self.ListProtocol.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">protocol</p></body></html>',
            )
        )
        self.ListInfo.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">info</p></body></html>',
            )
        )
        self.label_2.setText(_translate("MainWindow", "Packet Detail"))
        self.DetailText.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.label_4.setText(_translate("MainWindow", "Packet Binary"))
        self.Binarytext.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.menuSniffer.setTitle(_translate("MainWindow", "Sniffer"))
        self.menuDetail.setTitle(_translate("MainWindow", "List"))
        self.menuDetal.setTitle(_translate("MainWindow", "Detal"))
        self.menuBinary.setTitle(_translate("MainWindow", "Binary"))
